//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_Semestralny
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Przedmioty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Przedmioty()
        {
            this.Ocenies = new ObservableCollection<Oceny>();
        }
    
        public string Nazwa_Przedmiotu { get; set; }
        public int Prowadzacy_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Oceny> Ocenies { get; set; }
        public virtual Prowadzacy Prowadzacy { get; set; }
    }
}
