//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_Semestralny
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Uczniowie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uczniowie()
        {
            this.Ocenies = new ObservableCollection<Oceny>();
        }
    
        public int Legitymacja { get; set; }
        public string S_Imie { get; set; }
        public string S_Nazwisko { get; set; }
        public string Nazwa_Grupy { get; set; }
    
        public virtual Grupa Grupa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Oceny> Ocenies { get; set; }
    }
}
